name: React build flows
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout main source code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: create env file
        run: |
          touch .env
          echo BASE_URL=${{ secrets.ENV_PROD_BASE_URL }} >> .env
          echo OAUTH_GOOGLE=${{ secrets.ENV_PROD_OAUTH_GOOGLE }} >> .env
          echo OAUTH_NAVER=${{ secrets.ENV_PROD_OAUTH_NAVER }} >> .env
          echo VERSION=${{ secrets.ENV_PROD_VERSION }} >> .env
          echo SENTRY_DSN=${{ secrets.ENV_PROD_SENTRY_DSN }} >> .env
          echo AMPLITUDE_APP_KEY=${{ secrets.AMPLITUDE_APP_KEY }} >> .env
          echo FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} >> .env
          echo FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }} >> .env
          echo FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} >> .env
          echo FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }} >> .env
          echo FIREBASE_MESSAGE_SENDER_ID=${{ secrets.FIREBASE_MESSAGE_SENDER_ID }} >> .env
          echo FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }} >> .env
          echo FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }} >> .env
          cat .env
      - name: NPM build
        run: npm run build:prod
      - name: Setup Python for AWS CLI
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install AWS CLI
        run: pip3 install awscli --upgrade --user
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: true
      - name: S3 deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ${{ secrets.AWS_REGION }} \
            dist s3://career-zip.com
      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_PROD_DISTRIBUTION_ID }} --paths "/*"
